### ISSUE TITLE
Used to work but now it doesn't

### ISSUE THREAD

**Issue by ghost** [heroku-examples/go-websocket-chat-demo#2]
I had this working before with a fork I created and it worked great three months ago. But cloning and deploying to Heroku (existing and new Dynos) results in a application crash after some in-browser WS weirdness when users try to actually chat. Again, this used to work great before.

![screen shot 2016-06-13 at 5 40 40 pm](https://cloud.githubusercontent.com/assets/440298/16025668/53eb8ff2-318e-11e6-8ff9-00b1d0d11022.png)

Any ideas what happened?

Here's an example error shown in the logs before the app crashes:

```
2016-06-13T23:30:31.196804+00:00 app[web.1]: time="2016-06-13T23:30:31Z" level=error msg="Error while subscribed to Redis channel chat" err="dial tcp: missing address" 
```

**Comment by freeformz** [comment]
It seems like maybe it's trying to connect to the redis server and failing? If you tell me the app name I can go and check more.

**Comment by ghost** [comment]
@freeformz thanks for the quick response. `blooming-woodland-34351`. I backed up history to the head of the upstream repo and used the toolbelt to push the app here: http://lumpen-chat.habd.as/

**Comment by ghost** [comment]
Going to give this a shot locally and see if I can get it working with [dlite](https://github.com/nlf/dlite) this time around.

**Comment by freeformz** [comment]
So the problem with blooming-woodland-34351 is that there is no redis addon attached. The sample app uses redis to relay messages between instances. To resolve try this:

``` console
$ heroku addons:add heroku-redis
$ heroku redis wait
$ heroku restart
$ heroku open
```

I recently deployed this app to `https://limitless-coast-14277.herokuapp.com/` and it worked.

**Comment by ghost** [comment]
@freeformz thanks. that fixed the problem and helped me continue to appreciate the CLI more 😺

**Comment by freeformz** [comment]
Great. It's probably all possible via the dashboard as well, but it's
harder to script and relay that to others. I should also modify the program
to output a better set of errors as well. Btw: how was the app created?
With a button? Or via the cli?

**Comment by ghost** [comment]
This one was created via CLI after I wiped the last one after it fell over. Guessing I simply missed creating and attaching Redis this time around. I should probably add the Heroku steps to a [related blog post](http://habd.as/chat-applications-redis-docker-go/) I wrote so I don't forget next time.
